# Generated by Django 3.0.5 on 2020-05-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['pub_date']},
        ),
    ]
