# Generated by Django 3.0.5 on 2020-05-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='DZCS101', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='Computer Science', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(default='Computer Science', max_length=100, unique=True),
        ),
    ]
