# Generated by Django 3.0.5 on 2020-06-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200512_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
    ]
