# Generated by Django 3.0.5 on 2020-05-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_auto_20200507_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default='2020-04-19'),
        ),
    ]
